---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: content
        configMap:
          name: nginx-content
          defaultMode: 0444
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
  labels:
    app: nginx-demo
data:
  index.html: |-
    <h1>Hello Kubernetes!</h1>
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
